all: tcat tgrep tzip tunzip

tcat:
	gcc -Wall -Werror -o tcat tcat.c
tgrep:
	gcc -Wall -Werror -o tgrep tgrep.c
tzip:
	gcc -Wall -Werror -o tzip tzip.c
tunzip:
	gcc -Wall -Werror -o tunzip tunzip.c
clean:
	-rm tcat tgrep tzip tunzip
